version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    debug:
        addr: :5001
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
auth:
  htpasswd:
    realm: NewStore Docker Registry2
    path: /var/lib/registry/htpasswd
storage:
  filesystem:
      rootdirectory: /var/lib/registry